# Generated by Django 3.2 on 2022-02-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='SCustomerID',
        ),
        migrations.DeleteModel(
            name='BuyBooking',
        ),
        migrations.DeleteModel(
            name='SellCar',
        ),
    ]
