# Generated by Django 4.0.1 on 2022-02-05 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BAddress', models.TextField()),
                ('BPhoneNumber', models.BigIntegerField()),
                ('BBrandID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.buybrand')),
                ('BCarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buycar')),
                ('BCustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
