# Generated by Django 3.2 on 2022-01-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyspecs',
            name='Image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
