# Generated by Django 4.0.1 on 2022-02-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buybooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybooking',
            name='BCarID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buyspecs'),
        ),
    ]
