# Generated by Django 3.2 on 2022-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220202_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycar',
            name='BCarImage',
            field=models.BinaryField(),
        ),
    ]
