# Generated by Django 3.2 on 2022-02-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_buycar_bcarimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyspecs',
            name='Image',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='RImage',
            field=models.BinaryField(),
        ),
    ]
