# Generated by Django 4.0.1 on 2022-02-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_buybooking_bcarid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybooking',
            name='BPrice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.buyspecs'),
        ),
        migrations.AlterField(
            model_name='buybooking',
            name='BCarID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buycar'),
        ),
    ]
