# Generated by Django 4.0.1 on 2022-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_buybooking_sellcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFname', models.CharField(max_length=100)),
                ('CLname', models.CharField(max_length=100)),
                ('CEmail', models.EmailField(max_length=254)),
                ('CPhone', models.BigIntegerField()),
                ('CMessage', models.TextField()),
            ],
        ),
    ]
