# Generated by Django 4.0.1 on 2022-02-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_buybooking_bprice_alter_buybooking_bcarid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybooking',
            name='BPrice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.buyspecs'),
        ),
    ]
