# Generated by Django 3.2 on 2022-02-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220203_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyspecs',
            name='CarID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.buycar'),
        ),
    ]
