# Generated by Django 4.0.1 on 2022-07-13 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UFromDate', models.DateField()),
                ('UToDate', models.DateField()),
                ('UNoOfDays', models.IntegerField()),
                ('UBrandName', models.CharField(max_length=100)),
                ('UCarName', models.CharField(max_length=100)),
                ('UKmRun', models.IntegerField()),
                ('UCarAge', models.IntegerField()),
                ('UFuel', models.CharField(max_length=100)),
                ('UMileage', models.FloatField()),
                ('USeatingCapacity', models.IntegerField()),
                ('URentPerDay', models.IntegerField()),
                ('UTotalRent', models.IntegerField()),
                ('UPhoneNum', models.BigIntegerField()),
                ('UAddress', models.TextField()),
                ('UCustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
