# Generated by Django 4.0.1 on 2022-02-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_buybooking_bprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybooking',
            name='BPrice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.buyspecs'),
        ),
    ]
