# Generated by Django 3.2 on 2022-02-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_buyspecs_carid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybooking',
            name='BBrandID',
        ),
        migrations.AlterField(
            model_name='buyspecs',
            name='CarID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.buycar'),
        ),
    ]
