# Generated by Django 4.0.1 on 2022-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrent',
            name='URentPerDay',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userrent',
            name='UTotalRent',
            field=models.FloatField(),
        ),
    ]
