# Generated by Django 4.0.1 on 2022-02-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_buybooking_bprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybooking',
            name='BPrice',
        ),
    ]
