# Generated by Django 4.0.1 on 2022-02-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_buybooking_bprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybooking',
            name='BBrandID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buybrand'),
        ),
    ]
