# Generated by Django 3.2 on 2022-02-04 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_buyspecs_carid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybooking',
            name='BBrandID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.buybrand'),
        ),
    ]
