# Generated by Django 4.0.1 on 2022-02-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_buybooking_bbrandid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcar',
            name='SAddress',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='sellcar',
            name='SPhoneNum',
            field=models.BigIntegerField(default=None),
        ),
    ]
