# Generated by Django 4.0.1 on 2022-11-19 15:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_rentcar_rimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcar',
            name='SImage',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.filepath),
        ),
    ]
