# Generated by Django 3.2 on 2022-02-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_buybooking_bbrandid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybooking',
            name='BBrandID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buybrand'),
        ),
    ]
