# Generated by Django 4.0.1 on 2022-02-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sellcar_saddress_sellcar_sphonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcar',
            name='SAddress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='SPhoneNum',
            field=models.BigIntegerField(),
        ),
    ]
