# Generated by Django 3.2 on 2022-02-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_buybooking_bbrandid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybooking',
            name='BBrandID',
        ),
    ]
