# Generated by Django 3.2 on 2022-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_buybooking_bbrandid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybooking',
            name='BCarID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buybooking',
            name='BCustomerID',
            field=models.CharField(max_length=100),
        ),
    ]
