# Generated by Django 3.2 on 2022-02-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_auto_20220204_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybooking',
            name='BCarID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buycar'),
        ),
        migrations.AlterField(
            model_name='buybooking',
            name='BCustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
